
---
# ===@@@!!!PCI DSS vars!!!@@@===
lspadmin_password: Cdgbcdgb1@3

# ===@@@!!!patroni vars!!!@@@===
ansible_user            : centos
ansible_ssh_private_key : /Users/akatruk/.ssh/id_rsa.pub

cname1: srv1
ip_address1: 172.31.30.162
cname2: srv2
ip_address2: 172.31.31.177
cname3: srv3
ip_address3: 172.31.18.93
virtual_ip: 172.31.30.19
network_pg: '172.31.0.0/24'
cluster_name: demo

hosts: 172.31.30.162:2379, 172.31.22.61:2379, 172.31.18.93:2379
# patroni_scope: patroniscope

# ===@@@!!!access to database as postgres user !!!@@@===
password_postgres: '*******************'

# Posgres parameters
patroni_pg_max_connections: 100
shared_buffers: 1GB
work_mem: 10485kB
effective_cash_size: 3GB

# ====== vars VM deploy ======
vapp_name_vcd: k8s-prod_db
source_catalog_name: LSP OS Catalog
network: K8s-ProdDB-Int
storage_profile: LifeStyle-Platform-FAS-Medium
source_template_name: TEMPLATE
target_vdc: LifeStyle-Platform
virtual_cpus: 2
memory: 4096
Additional_Disk_Size: 51200
vm_name:
       - M1K8SPLDB10
       - M1K8SPLDB11
       - M1K8SPLDB12
ip_address: 
       - 10.10.11.11
       - 10.10.11.12
       - 10.10.11.13

       