
---
# ===@@@!!!PCI DSS vars!!!@@@===
lspadmin_password: Cdgbcdgb1@3

# ===@@@!!!patroni vars!!!@@@===
ansible_user            : katruk
ansible_ssh_private_key : /Users/akatruk/.ssh/id_rsa.pub

cname1: M1BKPPLAS02
ip_address1: 10.10.1.132
cname2: M1BKPPLAS04
ip_address2: 10.10.1.134
cname3: M1BKPPLAS05
ip_address3: 10.10.1.135
virtual_ip: 10.10.1.140
network_pg: '10.10.1.0/24'
cluster_name: cluster_test

pci_dss_active_node: M1BKPPLAS04
# pci_dss_active_ip_node: 10.10.1.134

hosts: 10.10.1.132:2379, 10.10.1.134:2379, 10.10.1.135:2379
# patroni_scope: patroniscope

# ===@@@!!!access to database as postgres user !!!@@@===
password_postgres: 'w4wKwFfNEfeb4p67k'

# Posgres parameters
patroni_pg_max_connections: 100
shared_buffers: 1GB
work_mem: 10485kB
effective_cash_size: 3GB

# ====== vars VM deploy ======

source_catalog_name: LSP OS Catalog
network: DevTools-Int
storage_profile: LifeStyle-Platform-FAS-Medium
source_template_name: TEMPLATE
target_vdc: LifeStyle-Platform
virtual_cpus: 2
memory: 2048
Additional_Disk_Size: 10240
vm_name:
       - pgtest01