
---
# ===@@@!!!PCI DSS vars!!!@@@===
lspadmin_password: Cdgbcdgb1@3

# ===@@@!!!patroni vars!!!@@@===
# ansible_user            : katruk
# ansible_ssh_private_key : /Users/akatruk/.ssh/id_rsa.pub

cname1: M1CRMPLDB02
ip_address1: 10.10.11.104
cname2: M1CRMPLDB03
ip_address2: 10.10.11.105
cname3: M1CRMPLDB04
ip_address3: 10.10.11.106
virtual_ip: 10.10.11.110
network_pg: '10.10.11.0/24'
cluster_name: CRMDB

hosts: 10.10.11.104:2379, 10.10.11.105:2379, 10.10.11.106:2379
patroni_scope: patroniscope

# ===@@@!!!access to database as postgres user !!!@@@===
password_postgres: 4wKwFfNEfeb4p67k

# Posgres parameters
patroni_pg_max_connections: 100
shared_buffers: 1GB
work_mem: 10485kB
effective_cash_size: 3GB

# ====== vars VM deploy ======

source_catalog_name: LSP OS Catalog
network: DevTools-Int
storage_profile: LifeStyle-Platform-FAS-Medium
source_template_name: TEMPLATE
target_vdc: LifeStyle-Platform
virtual_cpus: 2
memory: 2048
Additional_Disk_Size: 10240
vm_name:
       - pgtest01