
---
# ===@@@!!!PCI DSS vars!!!@@@===
lspadmin_password: Cdgbcdgb1@3

# ===@@@!!!patroni vars!!!@@@===
ansible_user            : root
ansible_ssh_private_key : /Users/akatruk/.ssh/id_rsa.pub

cname1: pg01
ip_address1: 10.1.200.18
cname2: pg02
ip_address2: 10.1.200.22
cname3: pg03
ip_address3: 10.1.200.26
virtual_ip: 10.1.200.205
network_pg: '10.1.200.0/24'
cluster_name: pg_cl

hosts: 10.1.200.18:2379, 10.1.200.22:2379, 10.1.200.26:2379
patroni_scope: patroniscope

# ===@@@!!!access to database as postgres user !!!@@@===
password_postgres: 4wKwFfNEfeb4p67k

# Posgres parameters
patroni_pg_max_connections: 30
shared_buffers: 512MB
work_mem: 128MB
effective_cash_size: 1536MB

# ====== vars VM deploy ======

source_catalog_name: LSP OS Catalog
network: DevTools-Int
storage_profile: LifeStyle-Platform-FAS-Medium
source_template_name: TEMPLATE
target_vdc: LifeStyle-Platform
virtual_cpus: 2
memory: 2048
Additional_Disk_Size: 10240
vm_name:
       - pgtest01