---
  
  - name: Lynis | add repo
    copy:
      src: lynis.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: '0644'   

  - name: Lynis | install
    yum:
      name: lynis
      update_cache: yes
      state: latest

  - name: Lynis | pentest
    shell:
      cmd: lynis --pentest

  - name: Lynis | report suggestions
    shell: "grep 'suggestion' {{ lynis_report }}"
    register: grep_output
    ignore_errors: true

  - debug:
      var: grep_output.stdout_lines
    when: grep_output.stdout != ""  