---

- name: Install PostgreSQL patroni
  hosts: patroni
  become: yes

  roles:
    #  - equipping
    #  - etcd
    #  - postgresql
    #  - haproxy
    #  - keepalived
     - pci
    #  - barman_client
    #  - barman_server
    #  - postgresql_standalone
    #  - pci_dss
    #  - timezone