---

- name: Install PostgreSQL patroni
  hosts: crm
  remote_user: katruk
  become: yes

  roles:
    #  - equipping
    #  - etcd
    #  - postgresql
    #  - haproxy
    #  - keepalived
    #  - barman_client
    #  - barman_server
    #  - postgresql_standalone
     - pci_dss