---
    # Установить все последние обновления безопасности.
    # Отключить и удалить весь неиспользуемый и ненужный функционал.
    # Изменить или заблокировать все встроенные в учетные записи.
    # Обеспечить обязательную аутентификацию доступа (локального или удаленного).
    # Настроить привилегии доступа административных учетных записей и учетных записей пользователей.
    # Настроить механизм регистрации действий пользователей и администраторов.
    # Настроить механизм шифрования не консольного административного и пользовательского доступа.

 - name: upgrade all packages
   yum:
      name: postgresql-12
      state: latest
   
