---
# tasks file for keepalived  
- name: Install keepalived
  yum: name=keepalived state=latest

- name: put config
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes

- name: restart and enable
  service: name=keepalived state=restarted enabled=yes

# - name: pause
#   pause:
#     seconds: 20