---

- name: Add the user 'postgres' with a primary group of 'postgres'
  user:
    name: postgres
    comment: postgres user

- name: Install PosrgreSQL wget
  yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm state=present

- name: Disable
  command: dnf -qy module disable postgresql

- name: Install PostgreSQL
  dnf: name={{ item }} state=latest
  with_items:
    - postgresql12
    - postgresql12-server
    - postgresql12-contrib

- name: remove old PostgreSQL
  command: rm -rf /var/lib/pgsql/
  become: true

- name: Install cluster PostgreSQL
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  become: true

- name: enable cluster PostgreSQL
  command: systemctl enable postgresql-12
  become: true

- name: start cluster PostgreSQL
  command: systemctl start postgresql-12
  become: true

- name: логирование событий
  blockinfile:
     path: /var/lib/pgsql/12/data/postgresql.conf
     block: |
        log_destination=syslog
        logging_collector=off
        syslog_facility = 'LOCAL0'
        syslog_ident = 'postgres'
        debug_pretty_print = on
        log_statement = 'all'
        log_connections = on
        log_disconnections = on
        log_min_messages=INFO
        log_min_error_statement=INFO
        password_encryption ='scram-sha-256'
        listen_addresses = '*'

- name: pg_hba sha256
  blockinfile:
      path: /var/lib/pgsql/12/data/pg_hba.conf
      block: |
        host    all             all             10.11.251.0/24          scram-sha-256
        host    all             all             192.168.13.0/24         scram-sha-256
        host    all             all             192.168.160.0/24        scram-sha-256
        host    all             all             10.11.3.11/32           scram-sha-256
        host    all             backup          10.10.1.130/24          trust
        local   replication     backup                                  peer
        host    replication     all             127.0.0.1/32            ident
        host    replication     all             ::1/128                 ident

      
- name: open firewall
  shell: firewall-cmd --permanent --add-port=5432/tcp
   
- name: reload firewall
  shell: firewall-cmd --reload

- name: restart postgres
  service:
    name: postgresql-12.service
    state: restarted